language: python
cache: pip
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7


install: "make deps deps-python-master"
script: "make lint coverage"
after_success: "codecov"


deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: 3.6
  user: beerbuildbot
  password:
    secure: eRzIInKTfL5vu5UnF6QyE+L/GVadvVv1v/8Z8wP56DgdzBnkTgiQWzBKfsWtxDRmI8atGWyz0SatopkcTEePYucsZgIZXTFRqWJ8OiqanKylBV/r+0Cg14ADltdAipcsi3rK3I67v0kIiW823vdqSNbW0CcLjZfeiVXFObp8i8ARKF2XDjJhl4i1PK81+4e9nKlP6gTAEsvU31KM+tFD2fQsDfyQgY3s24yoCU6MpWsiWR03YHDFSWgbALhzyJaWOgtQIIMZJOKoqfhhtU9uwAVHx8nNxs2TMzd2hzNfITGaHrGWuyYtH2dbebcv9Mn3Vvl1cjv31ZU3EzxoU5lgM9twmxtMVXjcHzZEV9iH1AjS88zyTCXH8fjP5AGDANBYhOVB6PfvwRg70Sw645P+adPQBGkva3KDSKbbWgJg4ZdiVEYaZVMySZbaNueArDBH3uEtmPRVyikjH30xUb8SKx1k6wLmpBeOfbWru9WYkQ7pFLN5HWJdvta39U0oRFevpqCF5maEqYeeyxvfk7pnUwabVbRbTPXmeozhOMReMrnzUUSAF2hvJIcGshVp6AAi/4nUIGUqkbpYr0/xkauWpxrKnM7YghMGLniWK2d1od0EKXijat6nqtJxQB/+Xn5lzwSGWZCQi0I3dz5uD99ZdhqN2z6Om7XweP9/8vLWLh0=

notifications:
  slack:
    secure: ODTX+6tZu+unnuliHiVrnQgm1Zp9Evi15vgz0JxX93SKoQ+gpw63PR+bTsGlZIOHPjTdZtT/mF7HvJlNKX1t/hsKS6tAVvCFJbnBDUHnSifBh3HFB6kJrVHHEVOMsgKy9nJ5vO6JBi1pwswEgpLndbONj6SAWF5pNJOT9IV6ju0fJDHnByh5uDHso/5aloO6Fg1tstrSQZ2p8AJXI2bTUPsDmShhntEHmbzK/IfwXCQ5WSehApkUGkzDTSf7PePOUNJpZ/7yJSihvGrrzd1gTmTM31Jg0gdOUkDVNfvKEEb14Wth9FruYZIQSNMHiVtb+P+8sCLhzDlLp3ZKIzEWIXTrNI3ELsnBCswQ6trVdy8AwCmh5Juaiwmnth32+a7FZ3nJSzr1WyP9kE4Ka8X1aRQtGme8TAvKWA/T5FSKp0W5+vQWWTybqrAo2I0V6KT5KemaQzxSdt/SYRhsRBcq/zPjerjmcyF3EGfEaWBN1bS+JyM0lX9SC7wt2I0XTUE3LZ70mKn1LJwto3gS2ENAf6LXmCLGEt9TAJub6Xfrd2IJCWniiwreBu01dfwyzkDr/D+l+3n7vR1PIf4GWZghw/nA1xBdRDi3euMBi9GKjiIulhZpt1QhbuAwYTuHPVkU6ALN5hwgtcwr9xGgbjzcP9HMnXvADkJSMI6Tt3HNESg=
