install: pip install -U tox-travis codecov
language: python
cache: pip
python:
- 3.6
- 3.5
- 3.4
- 2.7
script: tox
after_success: codecov
notifications:
  slack:
    secure: ODTX+6tZu+unnuliHiVrnQgm1Zp9Evi15vgz0JxX93SKoQ+gpw63PR+bTsGlZIOHPjTdZtT/mF7HvJlNKX1t/hsKS6tAVvCFJbnBDUHnSifBh3HFB6kJrVHHEVOMsgKy9nJ5vO6JBi1pwswEgpLndbONj6SAWF5pNJOT9IV6ju0fJDHnByh5uDHso/5aloO6Fg1tstrSQZ2p8AJXI2bTUPsDmShhntEHmbzK/IfwXCQ5WSehApkUGkzDTSf7PePOUNJpZ/7yJSihvGrrzd1gTmTM31Jg0gdOUkDVNfvKEEb14Wth9FruYZIQSNMHiVtb+P+8sCLhzDlLp3ZKIzEWIXTrNI3ELsnBCswQ6trVdy8AwCmh5Juaiwmnth32+a7FZ3nJSzr1WyP9kE4Ka8X1aRQtGme8TAvKWA/T5FSKp0W5+vQWWTybqrAo2I0V6KT5KemaQzxSdt/SYRhsRBcq/zPjerjmcyF3EGfEaWBN1bS+JyM0lX9SC7wt2I0XTUE3LZ70mKn1LJwto3gS2ENAf6LXmCLGEt9TAJub6Xfrd2IJCWniiwreBu01dfwyzkDr/D+l+3n7vR1PIf4GWZghw/nA1xBdRDi3euMBi9GKjiIulhZpt1QhbuAwYTuHPVkU6ALN5hwgtcwr9xGgbjzcP9HMnXvADkJSMI6Tt3HNESg=
