install: pip install -U tox-travis codecov
language: python
cache: pip
python:
- 3.6
- 3.5
- 3.4
- 2.7
script: tox
after_success: codecov
notifications:
  slack:
    secure: VF5UDvw6N2S4/umJronGPklBT4U0IMWGCRRPeD9o4tTHzV4pCiR3enrx+QkXdlArE7YlN6Ba0M+627hWr8wvSerbMQtJa/QIVp4c1ZxBrp5T8bg8ADnH1WJ9GNh5wkbrGd0DFusAL0nfqb7BvmnO1NGA7+dmT5JGjSNu5Z3yPsKE0V1BuN4o9YVveaVgIepdAA3oWkNayh6xxcBg1VXmyme0960pNttX0+ZQkPoyTApDGGw/k3U6BhK9DpIkkHrN5XoM5wZPMONBJJNn4rKLJSwkV+VsCbSeHS0WO06BnPjng7oojWiSNVY0uMXetBEMQKxhvHaBPVtD9GO3WrJGpcIA2kzZxV51BNhOD2eKSQLyA7x4Kq9fUJNxblI9ppxUq0RZYp/IhvjVxsB1jAxyisBNTtTzoqPFfNk9lpWriiODwAF+5jidR+KcWH5BMvjz+bg47GJ+fwWpiaqjb8X4iNMiYu9l3r5GcXR6iXsSopTlnptJYas1jm4A1Vdj0D2Lz7iCl94Bt92ClFTDdRxFxS9rV2IzhlTu7AtkAyzZHA8OnBveJH5h8xnWl2WNEFdA/Kw74ngrE01TeDTNDSMFo+5dW2X0bkgGBtScmBhMNlLCQ9PCpIs7c0SdSaWLkQQhetIgs4NIjNfVmRryR5tuZInBlk1oW8Z8gCggepgBt2o=
