version: '3.5'

x-definitions: &env
    # Change this to support remote plugins outside of docker
    # Should be resolvable from inside and outside the docker network
    BG_AMQ_PUBLISH_HOST: rabbitmq

    BG_AMQ_ADMIN_HOST: rabbitmq
    BG_AMQ_ADMIN_USER: beer_garden
    BG_AMQ_ADMIN_PASSWORD: password
    BG_AMQ_HOST: rabbitmq
    BG_AMQ_USER: beer_garden
    BG_AMQ_PASSWORD: password
    BG_BACKEND_HOST: bartender
    BG_DB_HOST: mongodb
    BG_WEB_HOST: brew-view

services:
    brew-view:
        image: bgio/brew-view
        networks:
            - bg-network
        ports:
            - "2337:2337"
            - "2338:2338"
        environment:
            <<: *env
            # We expose grafana for you, but you can change this to an
            # external grafana URL if you would like. It just adds a
            # link in our About section if it is defined.
            BG_METRICS_URL: http://localhost:3000
        depends_on:
            - mongodb
            - rabbitmq

    bartender:
        image: bgio/bartender
        networks:
            - bg-network
        volumes:
            - ./localplugins:/plugins
        environment:
            <<: *env
        depends_on:
            - mongodb
            - rabbitmq
            - brew-view

    grafana:
        image: grafana/grafana:5.2.3
        ports:
            - "3000:3000"
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        networks:
            - bg-network
        depends_on:
            - prometheus

    mongodb:
        image: mongo:3.6
        networks:
            - bg-network
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb
        restart: always

    prometheus:
        image: prom/prometheus:v2.3.2
        ports:
          - "9091:9090"
        networks:
            - bg-network
        volumes:
            - ./prometheus:/prometheus-data
        command:
            --config.file=/prometheus-data/prometheus.yml

    rabbitmq:
        image: rabbitmq:management-alpine
        networks:
            - bg-network
        environment:
            - RABBITMQ_DEFAULT_USER=beer_garden
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - "5672:5672"
        volumes:
            - rabbitmq-home:/var/lib/rabbitmq

networks:
    bg-network:
        driver: bridge
        name: bg-network

volumes:
    plugins:
    plugin-logs:
    mongo-data:
    mongo-config:
    rabbitmq-home:
