version: '2'

services:
    brew-view:
        image: bgio/brew-view
        command: brew-view -c /conf/brew-view-config.json
        networks:
            - bg-network
        ports:
            - "2337:2337"
        volumes:
            - ./conf:/conf
        depends_on:
            - mongodb
            - rabbitmq

    bartender:
        image: bgio/bartender
        command: bartender -c /conf/bartender-config.json
        networks:
            - bg-network
        volumes:
            - ./plugins:/plugins
            - ./conf:/conf
        depends_on:
            - mongodb
            - rabbitmq
            - brew-view

    mongodb:
        image: mongo:3.4
        networks:
            - bg-network
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb

    rabbitmq:
        image: rabbitmq:3.6-management-alpine
        networks:
            - bg-network
        environment:
            - RABBITMQ_DEFAULT_USER=beer_garden
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - "5672:5672"
        volumes:
            - rabbitmq-home:/var/lib/rabbitmq

networks:
    bg-network:
        driver: bridge

volumes:
    plugins:
    plugin-logs:
    mongo-data:
    mongo-config:
    rabbitmq-home:
