# name: Complexity

# on: pull_request

# jobs:
#   ComplexityCheck:
#     runs-on: ${{ matrix.os }}

#     strategy:
#       matrix:
#         python-version: ['3.7']
#         os: ['ubuntu-latest']
#         complexity-threshold: ['10']
#         # This strips the line and column from the output, but keeps the file name
#         sed-filter: ['s"/([^:]+):([^:]+):([^:]+):*/\1:/"']

#     env:
#       OS: ${{ matrix.os }}
#       PYTHON: ${{ matrix.python-version }}

#     name: Code Complexity Check OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
#     steps:
#       - name: Setup python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Make Deps
#         run: |
#           python -m pip install --upgrade pip
#           pip install wily

#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.base_ref }}
#           path: ./old

#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.head_ref }}
#           path: ./new

#       - name: Scan current complexity
#         working-directory: ./new/src/app
#         run: |
#           flake8 --max-complexity ${{ matrix.complexity-threshold }} | sed -E ${{ matrix.sed-filter }} > ~/current_complexity.txt

#       - name: Scan old complexity
#         working-directory: ./old/src/app
#         run: |
#           flake8 --max-complexity ${{ matrix.complexity-threshold }} | sed -E ${{ matrix.sed-filter }} > ~/old_complexity.txt

#       - name: Compare complexities
#         working-directory: ./new/.github/workflows/complexity
#         run: |
#           python parse_diff_complexity.py "$HOME/old_complexity.txt" "$HOME/current_complexity.txt"
