amq:
  connection_attempts: 3
  connections:
    admin:
      password: guest
      port: 15672
      user: guest
    message:
      password: guest
      port: 5672
      user: guest
  exchange: beer_garden
  heartbeat_interval: 3600
  host: localhost
  virtual_host: /
application:
  allow_unsafe_templates: false
  icon_default: fa-beer
  name: Beer Garden
auth:
  enabled: False
  token:
    algorithm: HS256
    lifetime: 1200
    secret: IAMSUPERSECRET
backend:
  host: localhost
  port: 9090
  socket_timeout: 3000
configuration:
  file: dev_conf/config.yml
  type: yaml
cors_enabled: true
db:
  connection:
    host: localhost
    password: null
    port: 27017
    username: null
  name: beer_garden
debug_mode: true
event:
  amq:
    enable: true
    exchange: event
    virtual_host: /
  mongo:
    enable: true
  public_fqdn: localhost
log:
  config_file: dev_conf/logging-config.json
  file: null
  level: INFO
metrics:
  port: 2338
  url: http://localhost:3000
plugin_logging:
  config_file: null
  level: INFO
scheduler:
  max_workers: 10
  job_defaults:
    coalesce: True
    max_instances: 3
shutdown_timeout: 5
web:
  host: 0.0.0.0
  port: 2337
  ssl:
    ca_cert: null
    ca_path: null
    client_cert_verify: NONE
    enabled: false
    private_key: null
    public_key: null
  url_prefix: null
