application:
  allow_unsafe_templates: false
  cors_enabled: true
  debug_mode: true
  icon_default: fa-beer
  name: Beer Garden
auth:
  enabled: true
  guest_login_enabled: true
  token:
    algorithm: HS256
    lifetime: 1200
    secret: IAMSUPERSECRET
backend:
  host: localhost
  port: 9090
  socket_timeout: 13000
db:
  connection:
    host: localhost
    password: null
    port: 27017
    username: null
  name: beer_garden_v3
log:
  config_file: dev_conf/logging-config.json
  file: null
  level: INFO
metrics:
  prometheus:
    enabled: true
    host: 0.0.0.0
    port: 2338
    url: http://localhost:3000
shutdown_timeout: 5
web:
  host: 0.0.0.0
  port: 2337
  public_fqdn: localhost
  ssl:
    ca_cert: null
    ca_path: null
    client_cert_verify: NONE
    enabled: false
    private_key: null
    public_key: null
  url_prefix: null
