name: Integration-Actions

on: pull_request

jobs:
  Plugin-Local-Testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.7']
        os: ['ubuntu-latest']
        plugin-brewtils: ['3.1.0']

    name: Plugin Local Test - OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - Brewtils ${{matrix.plugin-brewtils}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Docker Mongo
        run: docker-compose up -d mongodb
        working-directory: ./docker/docker-compose

      - name: Run Docker Rabbit
        run: docker-compose up -d rabbitmq
        working-directory: ./docker/docker-compose

#      - name: Build Local Beer Garden Docker
#        run: make docker-build VERSION=3
#        working-directory: ./src/app
      - uses: actions/checkout@v2
        with:
          repository: beer-garden/example-plugins
          path: ./docker/docker-compose/data/localplugins

      - name: Run Docker Beer Garden
        run: docker-compose up -d beer-garden
        working-directory: ./docker/docker-compose

      - name: Check Docker Containers
        run: docker ps

      - name: Uninstall Brewtils
        run: pip uninstall brewtils

      - name: Install Test Version of Brewtils
        run: pip install brewtils==${{matrix.plugin-brewtils}}

      - name: Install Python Deps
        run: pip install -r requirements.txt
        working-directory: ./test/integration

      - name: Test Rest
        run: make test-rest
        working-directory: ./test/integration

      - name: Shutdown Docker Containers
        run: docker-compose stop
        working-directory: ./docker/docker-compose