name: Integration-Actions

on: pull_request

jobs:
  Plugin-Testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.7']
#        python-version: [ '2.7', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9']
        os: ['ubuntu-18.04']
        plugin-brewtils: ['3.1.0']
#        plugin-brewtils: ['3.0.0','3.0.1','3.0.2','3.1.0']
      fail-fast: false

    name: Plugin Testing - OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - Brewtils ${{matrix.plugin-brewtils}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Docker Mongo
        run: docker-compose up -d mongodb
        working-directory: ./docker/docker-compose

      - name: Run Docker Rabbit
        run: docker-compose up -d rabbitmq
        working-directory: ./docker/docker-compose

#      - name: Build Local Beer Garden Docker
#        run: make docker-build VERSION=3
#        working-directory: ./src/app

      - name: Checkout Local Plugins
        uses: actions/checkout@v2
        with:
          repository: beer-garden/example-plugins
          path: ./docker/docker-compose/data/localplugins

      - name: Verify Local Plugins
        run: ls ./docker/docker-compose/data/localplugins

      - name: Set Timezone
        run: sed -i 's/#TZ:/TZ:/g' docker-compose.yml
        working-directory: ./docker/docker-compose

      - name: Run Docker Beer Garden
        run: docker-compose up -d beer-garden
        working-directory: ./docker/docker-compose

      - name: Check Docker Containers
        run: docker ps

      - name: Wait for Beer Garden to intialize
        run: sleep 30

      - name: Grab logs from Beer-Garden
        run: docker-compose logs --tail 100 beer-garden
        working-directory: ./docker/docker-compose

      - name: Uninstall Brewtils
        run: pip uninstall brewtils

      - name: Install Test Version of Brewtils
        run: pip install brewtils==${{matrix.plugin-brewtils}}

      - name: Install Python Deps
        run: pip install -r requirements.txt
        working-directory: ./test/integration

      - name: Test Plugins
        run: make test-plugins
        working-directory: ./test/integration

      - name: Shutdown Docker Containers
        run: docker-compose stop
        working-directory: ./docker/docker-compose