name: PR-Actions

on: pull_request

jobs:
  Linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/app
    strategy:
      matrix:
        python-version: ['3.8']
    name: Linting Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Linting
        run: |
          pip install black flake8
          make lint

  PyTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/app
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    name: PyTests Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make Deps
        run: make deps

      - name: Run Tests
        run: make test

