name: PR-Actions

on: pull_request

jobs:
  Linting:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./src/app

    strategy:
      matrix:
        python-version: ['3.7']
        os: ['ubuntu-latest']

    name: Linting Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Linting
        run: |
          pip install black flake8
          make lint

  PyTest:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./src/app

    strategy:
      matrix:
        python-version: ['3.7', '3.8']
        os: ['ubuntu-latest']

    name: PyTests Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make Deps
        run: make deps

      - name: Run Tests
        run: make test

  CodeCoverage:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./src/app

    strategy:
      matrix:
        python-version: ['3.7']
        os: ['ubuntu-latest']

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    name: Code Coverage Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make Deps
          run: make deps

      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
